"""add DockerFile and requirements.txt

Revision ID: 6e7cfbf60bc1
Revises: 1a444631090e
Create Date: 2025-09-14 23:05:51.191772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7cfbf60bc1'
down_revision: Union[str, Sequence[str], None] = '1a444631090e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
